<?php


/**
 * Implements hook_menu().
 */
function digital_maintenance_menu() {
  $items = array();
  $items['dm-frontpage'] = array(
    'title' => t('Digital Maintenance'),
    'page callback' => '_display_dm_task_frontpage',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['dm_createtask/%ctools_js'] = array(
    'title' => t('Create Task'),
    'page callback' => 'ctools_ajax_modal_createtask',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'page arguments' => array(1),
  );
  return $items;
}

/**
* Implements hook_form_FORM_ID_alter().
*/
function digital_maintenance_form_dm_task_node_form_alter(&$form, &$form_state, $form_id) {
  if (isset($_POST['js']) || isset($_POST['ajax_html_ids'])) {
    $form['actions']['submit']['#submit'][] = '_create_task_submit';
  }
}

function _create_task_submit($form, &$form_state) {
  // Call the rest of submits, because after this submit script will end.
  $submits = $form['actions']['submit']['#submit'];
  // Find the rest of submits.
  foreach ($submits as $key => $item) {
    unset($submits[$key]);
    if ($item == '_create_task_submit') {
      break;
    }
  }
  // Call it.
  foreach ($submits as $function) {
    if (function_exists($function)) {
      $function($form, $form_state);
    }
  }
  // Redirect to destination, if set, or to node path.
  if (isset($_GET['destination'])) {
    $destination = drupal_get_destination();
    _createtask_ajax_redirect($destination['destination']);
  }
  else if (isset($form_state['redirect'])) {
    _createtask_ajax_redirect($form_state['redirect']);
  }
}

function _createtask_ajax_redirect($path) {
  ctools_include('modal');
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  $commands[] = ctools_modal_command_dismiss();
  $commands[] = ctools_ajax_command_redirect($path);
  print ajax_render($commands);
  exit();
}

function ctools_ajax_modal_createtask($ajax) {
  $callback = 'node_add';
  $args = array('dm_task');
  $_GET['q'] = 'node/add/dm-task';
  include_once(drupal_get_path('module', 'node') . '/node.pages.inc');
  if (function_exists($callback)) {
    $output = call_user_func_array($callback, $args);
    if ($ajax) {
      ctools_include('modal');
      ctools_include('ajax');
      if (is_array($output)) {
        $output = drupal_render($output);
      }
      $title = drupal_get_title();
      // If there are messages for the form, render them.
      if ($messages = theme('status_messages')) {
        $output = '<div class="messages">' . $messages . '</div>' . $output;
      }
      $command = array();
      $command[] = ctools_modal_command_display($title, $output);
      $commands = $command;
      if (empty($commands)) {
        $commands[] = ctools_modal_command_loading();
        if (!empty($_GET['destination'])) {
          $commands[] = ctools_ajax_command_redirect($_GET['destination']);
        }
      }
      print ajax_render($commands);
      exit();
    }
    else {
      return $output;
    }
  }
  else {
    return MENU_NOT_FOUND;
  }
}

function _display_dm_task_frontpage() {
  // Include the CTools tools that we need.
  ctools_include('ajax');
  ctools_include('modal');
  // create CTools' javascript to the page.
  ctools_modal_add_js();
  $links = array();
  $links[] = ctools_modal_text_button(t('Create Task'), 'dm_createtask/nojs', t('Create task'));
  $links[] = l(t('Annual Overview'), 'dm-annual-overview');
  $output = theme('item_list', array('items' => $links, 'title' => ''));
  return $output;
}

/**
 * Implements of hook_views_query_alter().
 */
function digital_maintenance_views_query_alter(&$view, &$query) {
  if ($view->name == 'tasks_annual_overview') {
    //change exposed task list filter to be BETWEEN instead on original = operator.
    if (isset($view->query->where[1]['conditions'][1])) {
      $view->query->where[1]['conditions'][1]['operator'] = 'BETWEEN';
      $view->query->where[1]['conditions'][1]['value'] = array($_GET['name'], $_GET['to_year']);
    }
  }
  if ($view->name == 'dm_task_list_row' && $view->current_display == 'attachment_1') {
    //append to tasks list all tasks[with Year to perform task + Maintenance interval] that match displayed annual year
    //for example if I have a tasks that have year to perform task = 2013 and Maintenance interval = 1 
    //so I should display this task when listing annual year = 2014
    $key_id = current(array_keys($view->query->where[0]['conditions'][0]['value']));
    $tid = $view->query->where[0]['conditions'][0]['value'][$key_id];
    $term_data = entity_load('taxonomy_term', array($tid));
    $year = $term_data[$tid]->name;
    $scosts = _dm_get_subsequent_cost();
    $tasks_nids = isset($scosts[$year]) ? explode(',', $scosts[$year]->nids) : array(0);
    $view->query->where[0]['conditions'][0]['field'] = "node.nid IN($key_id)";
    $view->query->where[0]['conditions'][0]['value'][$key_id] = $tasks_nids;
  }
}

/**
 * Implements of hook_form_alter().
 */
function digital_maintenance_form_views_exposed_form_alter(&$form, &$form_state) {
  //alter exposed filter for task list view to add [to] field.
  //original exposed filter expose on text filed
  //will alter views query to add this value to query
  //@see digital_maintenance_views_query_alter().
  if ($form['#id'] == 'views-exposed-form-tasks-annual-overview-page') {
    $form['name']['#size'] = 5;
    $form['to_year'] = array(
      '#type' => 'textfield', 
      '#title' => t('To'),
      '#size' => 5,
    );
  }
}

/**
 * Implements of hook_views_pre_render().
 */
function digital_maintenance_views_pre_render(&$view) {
  if ($view->name == 'tasks_annual_overview') {
    //override taxonomy description to list SUM on tasks cost.
    $scosts = _dm_get_subsequent_cost();
    $mcosts = _dm_get_maintenance_cost();
    foreach($view->result as &$row) {
      $total_cost = 0;
      $total_cost += isset($mcosts[$row->taxonomy_term_data_name]) ? $mcosts[$row->taxonomy_term_data_name]->mcost : 0;
      $total_cost += isset($scosts[$row->taxonomy_term_data_name]) ? $scosts[$row->taxonomy_term_data_name]->scost : 0;
      //$row->taxonomy_term_data_description = isset($scosts[$row->taxonomy_term_data_name]) ? $scosts[$row->taxonomy_term_data_name]->scost : NULL;
      $row->taxonomy_term_data_description = $total_cost;
    }
  }
}

/**
 * Group all tasks with same [Year to perform task + Maintenance interval]
 * return associative array with key = year and fileds 
 * 'dm_year' => annual year.
 * 'scost' => sum of subsequent cost to all corresponding tasks.
 * 'nids' => tasks nids separated by ','
 */
function _dm_get_subsequent_cost($year = 'ALL') {
  //TODO: cache query result for 5 min at least.
  $query = db_select('taxonomy_term_data', 'td');
  $query->join('field_data_field_dm_year_to_perform_task', 'ypt', 'td.tid = ypt.field_dm_year_to_perform_task_tid');
  $query->join('field_data_field_dm_maintenance_interval', 'mi', 'ypt.entity_id = mi.entity_id');
  $query->join('field_data_field_dm_subsequent_cost', 'sc', 'ypt.entity_id = sc.entity_id');
  //$query->join('node', 'n', 'ypt.entity_id = n.nid');
  $query->addExpression("mi.field_dm_maintenance_interval_value + td.name", 'dm_year');
  //$query->addExpression("GROUP_CONCAT(CONCAT('l(\"', n.title, '\", \"node/', n.nid, '\")') SEPARATOR ',')", 'node_links');
  $query->addExpression("GROUP_CONCAT(ypt.entity_id SEPARATOR ',')", 'nids');
  $query->addExpression("SUM(sc.field_dm_subsequent_cost_value)", 'scost');
  $query->groupBy('dm_year');
  $query->orderBy('dm_year');
  $result = $query->execute()->fetchAllAssoc('dm_year');
  if ($year == 'ALL') {
    return $result;
  }
  if(isset($result[$year])) {
    return $result[$year];
  }
  return array();
}

/**
 * Function to SUM 1st Maintenance cost for each year
 *
 */
function _dm_get_maintenance_cost($year = 'ALL') {
  //TODO: cache query result for 5 min at least.
  $query = db_select('taxonomy_term_data', 'td');
  $query->join('field_data_field_dm_year_to_perform_task', 'ypt', 'td.tid = ypt.field_dm_year_to_perform_task_tid');
  $query->join('field_data_field_dm_maintenance_cost', 'mc', 'ypt.entity_id = mc.entity_id');
  $query->addField('td', 'name');
  $query->addExpression("SUM(mc.field_dm_maintenance_cost_value)", 'mcost');
  $query->groupBy('name');
  $query->orderBy('name');
  $result = $query->execute()->fetchAllAssoc('name');
  if ($year == 'ALL') {
    return $result;
  }
  if(isset($result[$year])) {
    return $result[$year];
  }
  return array();
}
